version: '2'

services:
    nginx-proxy:
      image: jwilder/nginx-proxy
      container_name: nginx-proxy
      ports:
        - "80:80"
      volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro
      environment:
        - DEFAULT_HOST=afternoob.com
    redis:
      image: redis
      volumes:
        - ./redis-backup:/data
      ports:
        - "6379:6379"
    niceoppai_notify:
      container_name: newtoon-notify
      environment:
        VIRTUAL_HOST: 'notify.afternoob.com'
        VIRTUAL_PORT: 8080
      image: zier/niceoppai_notify
      ports:
        - "8080:8080"
      links:
        - redis
